server:
  port: 9090
  servlet.encoding:
    charset: UTF-8
    force-response: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/transport
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: HikariCP_SpringBatch
      autoCommit: false
      minimumIdle: 4
      maximumPoolSize: 50
      maxLifeTime: 120000
      leakDetectionThreshold: 60000
      idleTimeout: 60000
  jpa:
    open-in-view: false

logging:
  config: classpath:log4j2.xml

logbook:
  include:
    - /api/**
  exclude:
    - /actuator/**
    - /api/admin/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /webjars/swagger-ui/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: json
  strategy: body-only-if-status-at-least
  minimum-status: 100
